package com.kg.isignatureserver.web.services.signinfoservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2016-03-04T12:46:39.902+08:00
 * Generated source version: 2.4.0
 * 
 */
 
@WebService(targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", name = "SignInfoService")
@XmlSeeAlso({ObjectFactory.class})
public interface SignInfoService {

    @WebResult(name = "signsn", targetNamespace = "")
    @RequestWrapper(localName = "addSignInfo", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.AddSignInfo")
    @WebMethod
    @ResponseWrapper(localName = "addSignInfoResponse", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.AddSignInfoResponse")
    public java.lang.String addSignInfo(
        @WebParam(name = "image", targetNamespace = "")
        byte[] image,
        @WebParam(name = "imageExt", targetNamespace = "")
        java.lang.String imageExt,
        @WebParam(name = "signName", targetNamespace = "")
        java.lang.String signName,
        @WebParam(name = "keySN", targetNamespace = "")
        java.lang.String keySN,
        @WebParam(name = "iamgeWidth", targetNamespace = "")
        java.lang.String iamgeWidth,
        @WebParam(name = "imageHeight", targetNamespace = "")
        java.lang.String imageHeight
    );

    @WebResult(name = "signInfo", targetNamespace = "")
    @RequestWrapper(localName = "getSigninfoBySignSN", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.GetSigninfoBySignSN")
    @WebMethod
    @ResponseWrapper(localName = "getSigninfoBySignSNResponse", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.GetSigninfoBySignSNResponse")
    public com.kg.isignatureserver.web.services.signinfoservices.Signinfo getSigninfoBySignSN(
        @WebParam(name = "signSn", targetNamespace = "")
        java.lang.String signSn
    );

    @WebResult(name = "signInfos", targetNamespace = "")
    @RequestWrapper(localName = "getSignInfosByKeySN", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.GetSignInfosByKeySN")
    @WebMethod
    @ResponseWrapper(localName = "getSignInfosByKeySNResponse", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.GetSignInfosByKeySNResponse")
    public java.util.List<com.kg.isignatureserver.web.services.signinfoservices.Signinfo> getSignInfosByKeySN(
        @WebParam(name = "keySn", targetNamespace = "")
        java.lang.String keySn
    );

    @WebResult(name = "signInfos", targetNamespace = "")
    @RequestWrapper(localName = "getSigninfosByUserCode", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.GetSigninfosByUserCode")
    @WebMethod
    @ResponseWrapper(localName = "getSigninfosByUserCodeResponse", targetNamespace = "http://signinfoServices.services.web.iSignatureServer.kg.com/", className = "com.kg.isignatureserver.web.services.signinfoservices.GetSigninfosByUserCodeResponse")
    public java.util.List<com.kg.isignatureserver.web.services.signinfoservices.Signinfo> getSigninfosByUserCode(
        @WebParam(name = "userCode", targetNamespace = "")
        java.lang.String userCode
    );
}
