
/*
 * 
 */

package com.kg.isignatureserver.web.services.orginfoservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2016-03-11T16:28:16.507+08:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "OrginfoServiceService", 
                  wsdlLocation = "http://127.0.0.1:8080/iSignatureServer/services/OrginfoService?wsdl",
                  targetNamespace = "http://orginfoServices.services.web.iSignatureServer.kg.com/") 
public class OrginfoServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://orginfoServices.services.web.iSignatureServer.kg.com/", "OrginfoServiceService");
    public final static QName OrginfoServicePort = new QName("http://orginfoServices.services.web.iSignatureServer.kg.com/", "OrginfoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/iSignatureServer/services/OrginfoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrginfoServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/iSignatureServer/services/OrginfoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrginfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrginfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrginfoServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrginfoServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrginfoServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public OrginfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OrginfoService
     */
    @WebEndpoint(name = "OrginfoServicePort")
    public OrginfoService getOrginfoServicePort() {
        return super.getPort(OrginfoServicePort, OrginfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrginfoService
     */
    @WebEndpoint(name = "OrginfoServicePort")
    public OrginfoService getOrginfoServicePort(WebServiceFeature... features) {
        return super.getPort(OrginfoServicePort, OrginfoService.class, features);
    }

}
