
/*
 * 
 */

package com.kg.isignatureserver.web.services.keyinfoservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.0
 * 2016-03-04T11:26:45.851+08:00
 * Generated source version: 2.4.0
 * 
 */


@WebServiceClient(name = "KeyInfoServiceService", 
                  wsdlLocation = "http://127.0.0.1:8080/iSignatureServer/services/KeyInfoService?wsdl",
                  targetNamespace = "http://keyinfoServices.services.web.iSignatureServer.kg.com/") 
public class KeyInfoServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://keyinfoServices.services.web.iSignatureServer.kg.com/", "KeyInfoServiceService");
    public final static QName KeyInfoServicePort = new QName("http://keyinfoServices.services.web.iSignatureServer.kg.com/", "KeyInfoServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://127.0.0.1:8080/iSignatureServer/services/KeyInfoService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KeyInfoServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://127.0.0.1:8080/iSignatureServer/services/KeyInfoService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KeyInfoServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KeyInfoServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KeyInfoServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyInfoServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyInfoServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public KeyInfoServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns KeyInfoService
     */
    @WebEndpoint(name = "KeyInfoServicePort")
    public KeyInfoService getKeyInfoServicePort() {
        return super.getPort(KeyInfoServicePort, KeyInfoService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KeyInfoService
     */
    @WebEndpoint(name = "KeyInfoServicePort")
    public KeyInfoService getKeyInfoServicePort(WebServiceFeature... features) {
        return super.getPort(KeyInfoServicePort, KeyInfoService.class, features);
    }

}
